services:
  - type: web
    name: voila-notebook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila gen-expression.ipynb --port=$PORT --no-browser --Voila.ip=0.0.0.0

